SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `Vulture`.`Users` CHANGE COLUMN `DateCreated` `DateCreated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP  ;

ALTER TABLE `Vulture`.`ProductImage` 
DROP INDEX `fk_Product_Image_Product_ID` ;

ALTER TABLE `Vulture`.`TutorSubjects` 
DROP INDEX `fk_TutorSubjects_TutorID` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
